/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cat.gltf --transform 
Files: cat.gltf [4.26MB] > cat-transformed.glb [347.41KB] (92%)
Author: mark2580 (https://sketchfab.com/mark2580)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-murdered-soul-suspect-836312def1b84e588866500a2bf79f0f
Title: Cat [Murdered: Soul Suspect]
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cat-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_81} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Material_81} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_93} skeleton={nodes.Object_9.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/cat-transformed.glb')
