/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cyberpunk_car.gltf --transform 
Files: cyberpunk_car.gltf [29.39MB] > cyberpunk_car-transformed.glb [682.88KB] (98%)
Author: 4d_Bob (https://sketchfab.com/3d_Bob)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-car-b4301ff99d214d16a7a43708a5866bf0
Title: Cyberpunk car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cyberpunk_car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cb_car_export_cb_car_0.geometry} material={materials.cb_car} rotation={[Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/cyberpunk_car-transformed.glb')
