/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 monster_happy_oscar_creativo.gltf --transform 
Files: monster_happy_oscar_creativo.gltf [32.91MB] > monster_happy_oscar_creativo-transformed.glb [2.17MB] (93%)
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monster-happy-oscar-creativo-005296542a064663accc0ff1077de6a3
Title: Monster Happy Oscar creativo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/monster_happy_oscar_creativo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ojo_cristal_Ojo_cristal_0.geometry} material={materials.Ojo_cristal} position={[0, -0.001, -0.56]} />
      <mesh geometry={nodes.OJO1_OJO1_0.geometry} material={materials.OJO1} position={[0, -0.001, -0.56]} />
      <mesh geometry={nodes.OJO2_OJO2_0.geometry} material={materials.OJO2} position={[0, -0.001, -0.56]} />
      <mesh geometry={nodes.PM3D_Sphere3D_4_PM3D_Sphere3D_4_0.geometry} material={materials.PM3D_Sphere3D_4} position={[0, -0.001, -0.56]} />
      <mesh geometry={nodes.LENGUA_LENGUA_0.geometry} material={materials.LENGUA} position={[0, -0.001, -0.56]} />
      <mesh geometry={nodes.DIENTES_DIENTES_0.geometry} material={materials.DIENTES} position={[0, -0.001, -0.56]} />
    </group>
  )
}

useGLTF.preload('/monster_happy_oscar_creativo-transformed.glb')
